music:
  songs:
    - name: Windowscene
      genre: Electronic
    - name: The World Is Mine
      genre: Electronic
    - name: Si Un Jour
      genre: Psychedelic Rock
    - name: Tomorrow Never Knows
      genre: Psychedelic Rock
    - name: Chan Chan
      genre: Son
