server:
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://localhost/purchases?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


purchases:
  gameAdmins:
    - username: steamadmin
      password: steamadmin
      authorities: ROLE_ADMIN
    - username: steamapp
      password: steamapp
      authorities: ROLE_APP
