server:
  port: 9003

spring:
  data:
    mongodb:
      uri: mongodb://localhost/drhouse-treatments
patient:
  treatment: spend one day in the hospital bed
accountancy:
  url: http://localhost:9004/patients
